#Learning how to used Jupiter Notebook

##Basic commend

In [1]:
x = "Hello world!"

In [2]:
print(x)

Hello world!


In [3]:
import numpy as np

In [21]:
exams = np.asarray([[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]])

In [20]:
exams

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [6]:
my_list = [i for i in range(1000000)]

In [7]:
my_array = np.arange(1000000)

In [8]:
%time for _ in range(10): my_list2 = [x**2 for x in my_list]

CPU times: user 3.08 s, sys: 209 ms, total: 3.29 s
Wall time: 3.3 s


In [9]:
%time for _ in range(10):my_array_2 = my_array **2

CPU times: user 23.9 ms, sys: 18.7 ms, total: 42.6 ms
Wall time: 42.1 ms


In [10]:
print(my_array)

[     0      1      2 ... 999997 999998 999999]


In [11]:
print(my_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [12]:
one_dim = np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

In [13]:
one_dim.shape

(4,)

In [14]:
one_dim.ndim

1

In [15]:
one_dim_horizontal = np.array([[1,2,3,4]])
print(one_dim_horizontal.shape)
one_dim_horizontal

(1, 4)


array([[1, 2, 3, 4]])

In [16]:
one_dim_vertical = one_dim_horizontal.reshape(-1, 1)
one_dim_vertical

array([[1],
       [2],
       [3],
       [4]])

In [17]:
two_dim = np.array([[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]])

print("len: " + str(len(two_dim)))
print("shape: " + str(two_dim.shape))
print("ndim: " + str(two_dim.ndim))

len: 3
shape: (3, 4)
ndim: 2


In [18]:
two_dim.size

12

In [19]:
two_dim.itemsize

8

In [22]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [23]:
my_nested_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones(5)
np.ones((2,3))
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [32]:
arr_01 = np.array([5, 10, 20])
print(arr_01, arr_01.dtype)
arr_02 = np.array([5, 10, 20.0])
print(arr_02, arr_02.dtype)
arr_03 = np.array([5, 10, '20'])
print(arr_03, arr_03.dtype)

[ 5 10 20] int64
[ 5. 10. 20.] float64
['5' '10' '20'] <U21


In [33]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.diag([5, 0, 4, 1, 3, 2])

array([[5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 2]])

In [36]:
np.random.rand(5)

array([0.3670144 , 0.97305774, 0.8280087 , 0.95909282, 0.29861613])

In [37]:
np.random.rand(5,5)

array([[0.17761411, 0.08830851, 0.68064632, 0.405071  , 0.48921477],
       [0.11688111, 0.95209319, 0.86076909, 0.13773633, 0.71771099],
       [0.61182948, 0.86651715, 0.53818008, 0.7605392 , 0.00708077],
       [0.82370823, 0.20349757, 0.15385262, 0.85360971, 0.41888634],
       [0.32231715, 0.22336354, 0.4427124 , 0.77553355, 0.99506146]])

In [38]:
np.random.randint(1,100,10)

array([20, 46, 84, 36, 88, 90, 75, 91, 64, 98])

Task 1 - create 10 elements vector with value between 0 and 1 exclude limit value

In [81]:
random_ten_elements = np.random.rand(10)
#random_ten_elements = [random.rand() for number in random_ten_elements if number == 0]
random_ten_elements

array([0.96444153, 0.45385894, 0.12185288, 0.7653893 , 0.40083479,
       0.95171623, 0.3271007 , 0.85428716, 0.28843694, 0.78500328])

Task 2 - create matrix 5 x 5 where value in rows are equal and in columns is 0, 1, 2, 3, 4.

In [65]:
np.matrix(np.arange(25).reshape(5,5))

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [88]:
row = np.arange(5)

In [98]:
matrix = np.matrix.repeat(row, 5, axis = 0)
matrix2 = np.matrix([row, row, row, row, row])

In [99]:
matrix

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [97]:
matrix2

matrix([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

In [171]:
matrix_3 = np.zeros((5,5), dtype=np.int8) + np.arange(5)
matrix_3

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

##Module 7.5 - ndarray operations

In [100]:
my_arr = np.arange(21)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [101]:
my_arr[10]

10

In [103]:
my_arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [105]:
my_arr[5:15:5]

array([ 5, 10])

In [106]:
two_dim = np.array([[0,10,20],[5,15,25],[100,200,300]])
two_dim

array([[  0,  10,  20],
       [  5,  15,  25],
       [100, 200, 300]])

In [107]:
two_dim[0]

array([ 0, 10, 20])

In [108]:
two_dim[1][0]

5

In [109]:
two_dim[1:3,:2]

array([[  5,  15],
       [100, 200]])

In [110]:
my_arr = np.arange(25).reshape(5,5)
my_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
my_arr[(0,1)]

1

In [112]:
my_arr[(0,1),]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
my_arr[[0,1],[0,4]]

array([0, 9])

In [114]:
vals = np.array([100,5,0])
select = np.random.randint(0,3,size=(4,3))
select

array([[0, 0, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 0]])

In [115]:
vals[select]

array([[100, 100,   0],
       [  0,   5, 100],
       [100,   0,   5],
       [100,   5, 100]])

In [116]:
vals[[1,0,2]]

array([  5, 100,   0])

In [117]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [119]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [120]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [121]:
fancy_arr = np.arange(10)
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
fancy_index_arr = fancy_arr[np.arange(5)]
fancy_index_arr

array([0, 1, 2, 3, 4])

In [123]:
fancy_index_arr[:] = 100
fancy_index_arr

array([100, 100, 100, 100, 100])

In [124]:
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
slice_of_arr.base is None

False

In [126]:
fancy_index_arr.base is None

True

In [127]:
slice_of_arr.base is arr

True

In [128]:
arr = np.arange(10)
print('arr')
print(arr)

slice_of_arr = arr[:5].copy()
print('slice_of_arr')
print(slice_of_arr)

slice_of_arr[:] = 100
print('slice_of_arr')
print(slice_of_arr)

print('arr')
print(arr)

arr
[0 1 2 3 4 5 6 7 8 9]
slice_of_arr
[0 1 2 3 4]
slice_of_arr
[100 100 100 100 100]
arr
[0 1 2 3 4 5 6 7 8 9]


In [129]:
slice_of_arr is arr

False

In [130]:
macierz = np.arange(9).reshape(3, 3)
print(macierz)
macierz[-1, -1] = 999
macierz[1:, 1:] = 0
print('\n', macierz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 0 0]
 [6 0 0]]


Task - find index of elements equals zero

In [136]:
index_elements_equels_zero = np.where(macierz == 0)
print(f"For index = {index_elements_equels_zero}")

For index = (array([0, 1, 1, 2, 2]), array([0, 1, 2, 1, 2]))


In [132]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [133]:
arr>15

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [137]:
arr[arr>15]

array([20, 25, 30, 35, 40, 45])

In [138]:
(arr>15) & (arr!=40)

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [139]:
arr[(arr>15) & (arr!=40)]

array([20, 25, 30, 35, 45])

In [140]:
(arr<10) | (arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [141]:
arr[(arr<10) | (arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [142]:
np.logical_or(arr<10,arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [143]:
arr[np.logical_or(arr<10,arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [146]:
np.transpose(two_dim)

array([[  0,   5, 100],
       [ 10,  15, 200],
       [ 20,  25, 300]])

Task - take from arr = np.arange(0,50,5) where elements are <10 or >=20 and != 40

In [147]:
#todo

Task - create matrix 4x4 where diagonaly have "false" and rest is "true" using XOR

In [148]:
#todo

Module 7.5 - MIX

In [149]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [150]:
arr[[3,0,1],:3]

array([[15, 16, 17],
       [ 0,  1,  2],
       [ 5,  6,  7]])

In [151]:
arr.sum()

190

In [152]:
arr[arr.sum(axis=1)>10,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [153]:
arr[arr.sum(axis=1)>10]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

TASKS
1. Zwróć z macierzy arr wiersz o indeksie nr 2, lecz tylko dla tych kolumn, których suma przekracza 30.
2. Mamy dane dwie tablice: a i b. Stwórz program filtrujący wartości z b, które korespondują z elementami a i są większe od 100 i mniejsze od 110.
    a = np.array([97,101,105,111,117,125])
    b = np.array(['a','e','i','o','u','y'])
3. Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą i największą wartość dla każdego wiersza.
[[0 4 1]
[2 0 4]]
4. Mając tablicę np.arange(11), odwróć znak wszystkich elementów większych od 3 i mniejszych od 8.

Task 1

In [155]:
#todo

Task 2

In [156]:
#todo

Task 3

In [157]:
#todo

Taks 4

In [158]:
#todo

##Modul 7.5 - MATRIX

In [160]:
macierz_1 = np.array([[1,3,6],
                      [7,1,1],
                      [7,2,7]])

print(f'Macierz 1\n{macierz_1}')
macierz_2 = np.array([[-9,3,7],
                      [7,3,1],
                      [-1,-9,5]])

print(f'Macierz 2\n{macierz_2}')

Macierz 1
[[1 3 6]
 [7 1 1]
 [7 2 7]]
Macierz 2
[[-9  3  7]
 [ 7  3  1]
 [-1 -9  5]]


In [161]:
macierz_1 + macierz_2

array([[-8,  6, 13],
       [14,  4,  2],
       [ 6, -7, 12]])

In [162]:
np.add(macierz_1, macierz_2)

array([[-8,  6, 13],
       [14,  4,  2],
       [ 6, -7, 12]])

In [163]:
macierz_1 - macierz_2

array([[10,  0, -1],
       [ 0, -2,  0],
       [ 8, 11,  2]])

In [164]:
np.subtract(macierz_1, macierz_2)

array([[10,  0, -1],
       [ 0, -2,  0],
       [ 8, 11,  2]])

In [165]:
print(macierz_1 * 10)
print()
print(macierz_1 * macierz_2)

[[10 30 60]
 [70 10 10]
 [70 20 70]]

[[ -9   9  42]
 [ 49   3   1]
 [ -7 -18  35]]


In [166]:
macierz_1.dot(macierz_2)

array([[  6, -42,  40],
       [-57,  15,  55],
       [-56, -36,  86]])

In [172]:
macierz_2.dot(macierz_1)

array([[ 61, -10,  -2],
       [ 35,  26,  52],
       [-29,  -2,  20]])

In [173]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [174]:
arr + arr

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [175]:
arr * arr

array([    0,   100,   400,   900,  1600,  2500,  3600,  4900,  6400,
        8100, 10000])

In [176]:
arr - 5

array([-5,  5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [177]:
left_ = np.arange(10).reshape(5,2)
right_ = np.arange(5).reshape(5,1)

left_

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [178]:
right_

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [179]:
right_ * left_

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21],
       [32, 36]])

In [180]:
left_ * right_

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21],
       [32, 36]])

In [181]:
arr = np.arange(0,101,10)

np.sqrt(arr)

array([ 0.        ,  3.16227766,  4.47213595,  5.47722558,  6.32455532,
        7.07106781,  7.74596669,  8.36660027,  8.94427191,  9.48683298,
       10.        ])

In [182]:
np.sin(arr)

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666,
       -0.50636564])

In [183]:
np.multiply(arr,2)

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

TASKS
1. Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą i największą wartość dla każdego wiersza.
    [[0 4 1]
    [2 0 4]]
2. Stwórz wektor Z według następującego wzoru: np.random.uniform(0,1,10). Następnie znajdź element, który jest najbliższy wartości 0.5.
3. Stwórz wektor zawierający 20 losowych wartości, a następnie zamień jego największą wartość na 0.
4. Znajdź części całkowite tablicy, wykorzystując przynajmniej dwa różne sposoby.
    np.array([5, 0.0249139 , 0.11873564, 0., 0.72321586, 11308494, 0.29931472, 0.24439968, 0.61251754, 4])

Task 1

In [184]:
#todo

Task 2

In [185]:
#todo

Task 3

In [186]:
#todo

Task 4

In [187]:
#todo

............................

In [192]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [193]:
arr.sum()

550

In [194]:
arr.mean()

50.0

In [195]:
arr.min()

0

In [196]:
arr.max()

100

In [197]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d, '\n')
print(arr_2d.min(axis=0), '\n')
print(arr_2d.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[1 4 7]


In [198]:
np.median(arr)

50.0

In [200]:
np.var(arr)

1000.0

In [201]:
np.std(arr)

31.622776601683793

In [202]:
arr / arr

/var/folders/dl/n6r7g5t96w30wn8vg3gb44640000gn/T/ipykernel_9043/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [203]:
defaults = np.seterr(all='ignore')

In [204]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [205]:
_ = np.seterr(**defaults)

In [206]:
arr / arr

/var/folders/dl/n6r7g5t96w30wn8vg3gb44640000gn/T/ipykernel_9043/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [207]:
arr = np.random.randint(1,40,10)
arr

array([26, 10, 30, 36, 26, 15, 21, 18, 15, 16])

In [208]:
np.sort(arr)

array([10, 15, 15, 16, 18, 21, 26, 26, 30, 36])

In [209]:
print(arr)
np.sort(arr)
print(arr)
arr = np.sort(arr)
print(arr)

[26 10 30 36 26 15 21 18 15 16]
[26 10 30 36 26 15 21 18 15 16]
[10 15 15 16 18 21 26 26 30 36]


In [210]:
arr = np.sort(arr)[::-1]
arr

array([36, 30, 26, 26, 21, 18, 16, 15, 15, 10])

In [211]:
print(arr)
arr.sort()
print(arr)

[36 30 26 26 21 18 16 15 15 10]
[10 15 15 16 18 21 26 26 30 36]


In [212]:
arr2d = np.array([np.arange(1,6),np.arange(6,1,-1)]).reshape(5,2)
arr2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 4],
       [3, 2]])

In [213]:
np.sort(arr2d)

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 5],
       [2, 3]])

In [214]:
np.sort(arr2d,axis=0)

array([[1, 2],
       [3, 2],
       [3, 4],
       [5, 4],
       [5, 6]])

In [215]:
dt = np.dtype([('student','S10'),('exam1',int),('exam2',int)])

a = np.array([("Student A",89,74),("Student B",85,56),
              ("Student C", 93,44), ("Student D",83,92)],dtype=dt)

a

array([(b'Student A', 89, 74), (b'Student B', 85, 56),
       (b'Student C', 93, 44), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [216]:
np.sort(a,order='exam1')

array([(b'Student D', 83, 92), (b'Student B', 85, 56),
       (b'Student A', 89, 74), (b'Student C', 93, 44)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [217]:
np.sort(a,order='exam2')

array([(b'Student C', 93, 44), (b'Student B', 85, 56),
       (b'Student A', 89, 74), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [218]:
np.sort(a,order='exam2')[-1][0]

b'Student D'

In [222]:
arr = np.random.randint(1,40,10)
arr

array([ 8, 21, 11, 20,  8,  6, 12,  5,  5, 16])

In [223]:
np.argsort(arr)

array([7, 8, 5, 0, 4, 2, 6, 9, 3, 1])

TASK - Posortuj wektor arr w sposób malejący, biorąc pod uwagę wyniki z drugiego egzaminu